name: UMAPPlugin

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

# for matrix check https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners
jobs:
  prepare_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix_setup.outputs.matrix }}
    steps:
    - name: Get matrix from file
      id: matrix_setup
      uses: ManiVaultStudio/github-actions/matrix_setup@publicRulessupport
      
  cross-platform-build:
    name: Cross platform build
    needs: prepare_matrix
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include: ${{ fromJson(needs.prepare_matrix.outputs.matrix) }}

    steps:
      - name: Checkout the source
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Checkout the source - pull request
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Select Xcode for Mac only
        if: startsWith(runner.os, 'macOS')
        run: |
          sudo xcode-select -switch /Applications/Xcode_${{matrix.build-xcode-version}}.app

      - name: Setup python version
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Windows build
        if: startsWith(matrix.os, 'windows')
        uses: ManiVaultStudio/github-actions/conan_windows_build@publicRulessupport
        with:
          conan-visual-version: ${{matrix.build-cversion}}
          conan-visual-runtime: ${{matrix.build-runtime}}
          conan-build-type: ${{matrix.build-config}}
          conan-user: ${{secrets.LKEB_UPLOAD_USER}}
          conan-password: ${{secrets.LKEB_UPLOAD_USER_PASSWORD}}
          conan-pem: ${{secrets.LKEB_UPLOAD_CERT_CHAIN}}
          sentry-upload: startsWith(github.ref, 'refs/heads/release/')
          sentry-url: ${{secrets.LKEB_SENTRY_URL }}
          sentry-org: ${{secrets.LKEB_SENTRY_ORG }}
          sentry-project: ${{secrets.LKEB_SENTRY_PROJECT }}
          sentry-auth-token: ${{secrets.LKEB_SENTRY_AUTH_TOKEN }}

      - name: Linux build
        if: startsWith(matrix.os, 'ubuntu')
        uses: ManiVaultStudio/github-actions/conan_linuxmac_build@publicRulessupport
        with:
          conan-compiler: ${{matrix.build-compiler}}
          conan-compiler-version: ${{matrix.build-cversion}}
          conan-libcxx-version: ${{matrix.build-libcxx}}
          conan-build-type: ${{matrix.build-config}}
          conan-build-os: ${{matrix.build-os}}
          build-arch: ${{matrix.build-arch}}
          conan-user: ${{secrets.LKEB_UPLOAD_USER}}
          conan-password: ${{secrets.LKEB_UPLOAD_USER_PASSWORD}}
          conan-pem: ${{secrets.LKEB_UPLOAD_CERT_CHAIN}}
          conan-cc: gcc-${{matrix.build-cversion}}
          conan-cxx: g++-${{matrix.build-cversion}}

      - name: Mac build
        if: startsWith(matrix.os, 'macos')
        uses: ManiVaultStudio/github-actions/conan_linuxmac_build@publicRulessupport
        with:
          conan-compiler: ${{matrix.build-compiler}}
          conan-compiler-version: ${{matrix.build-cversion}}
          conan-libcxx-version: ${{matrix.build-libcxx}}
          conan-build-type: ${{matrix.build-config}}
          conan-build-os: ${{matrix.build-os}}
          build-arch: ${{matrix.build-arch}}
          conan-user: ${{secrets.LKEB_UPLOAD_USER}}
          conan-password: ${{secrets.LKEB_UPLOAD_USER_PASSWORD}}
          conan-pem: ${{secrets.LKEB_UPLOAD_CERT_CHAIN}}
